version: "3.9"

services:
  translategemma-grpc:
    build:
      context: .
      dockerfile: Dockerfile.grpc
    image: gemma-grpc:1102
    container_name: translategemma-grpc
    ports:
      - "50051:50051"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/models
      - TRANSFORMERS_CACHE=/models
      - TORCH_HOME=/models
    volumes:
      - ./models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]

