version: "3.9"

services:
  translategemma-flash:
    build:
      context: .
      dockerfile: Dockerfile
    image: gemma-flash:1102
    container_name: translategemma-flash
    ports:
      - "8000:8000"
    environment:
      - HF_TOKEN=${HF_TOKEN}
      - HF_HOME=/models
      - TRANSFORMERS_CACHE=/models
      - TORCH_HOME=/models
    volumes:
      - ../models:/models
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
